services:
  mlat-server:
    build: .
    image: mlat-server:local
    container_name: mlat-server
    ports:
      - "40147:40147"
      - "30004:30004"
    volumes:
      - ./workdir:/app/workdir
    command: ["--work-dir", "./workdir", "--client-listen", "0.0.0.0:40147", "--status-interval", "10", "--dump-pseudorange", "./workdir/pseudorange.json", "--beast-connect", "194.209.200.36:30004"]
